# These are supported funding model platforms

github: [FlechazoPh]
patreon: flechazo
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: https://github.com/FlechazoPh/QLDependency/blob/56396ba27ef724da859dc1517787f502db5be7c8/assets/4B6DD0C1-8ECE-4C09-A0F7-3B6A36F399E7.jpeg
